---
title: "Reproducible Research: Peer Assessment 1"
output:  
html_document:
keep_md: true
---
###### Author Vasudevan D
###### Date   09/Nov/2017 

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figures/',echo=TRUE, warning=FALSE, message=FALSE)

```

## Loading and preprocessing the data
```{r echo = TRUE}

## Load the Data
if(!file.exists('activity.csv')) {
  unzip('activity.zip')
}
 
actData <- read.csv("activity.csv")
summary(actData)

## Preprocess the Data for formatting the date fields
actData$date = as.Date(actData$date)

```

## What is mean total number of steps taken per day?
```{r echo = TRUE}

## Included R packages necessary for processing
library(dplyr)

## Calculate the total number of steps taken per day
s1 <- group_by (actData, date)
stepsperday <- summarize(s1, stepsTotal = sum(steps, na.rm = TRUE))
print(stepsperday)

## If you do not understand the difference between a histogram and a barplot, research the difference between them. Make a histogram of the total number of steps taken each day
hist(stepsperday$stepsTotal, main = "Total Steps Analysis", xlab = "Total Steps")

## Calculate and report the mean and median of the total number of steps taken per day
medianStepsperday <- median(stepsperday$stepsTotal)
meanStepsperday <- mean(stepsperday$stepsTotal)

## Median Steps per day 
print(medianStepsperday)

## Mean Steps per day 
print(meanStepsperday)

```

## What is the average daily activity pattern?
```{r echo = TRUE}
## Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
s2 <- group_by (actData, interval)
avgstepsperInterval <- summarize(s2, avgs = mean(steps, na.rm = TRUE))
print(avgstepsperInterval)

plot(avgstepsperInterval$interval, avgstepsperInterval$avgs, type = "l", main = "Average Daily Activity Pattern", xlab = "Intervals", ylab = "Average Steps")

##Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
maxStepsPerInterval <-avgstepsperInterval[which.max(avgstepsperInterval$avgs),]$interval
print(maxStepsPerInterval)

```

## Inputing missing values

```{r echo = TRUE}

## Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
totMisValues <- sum(is.na(actData$steps))
print (totMisValues)

## Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc

## The Strategy to input the missing values would be mean for that interval and below function returns mean value for that interval 

getMissingValue <- function(interval) {
    avgstepsperInterval[avgstepsperInterval$interval == interval,]$avgs
}
    
## Create a new dataset that is equal to the original dataset but with the missing data filled in
refData <- actData
for (i in 1:nrow(refData))
{
 if(is.na(refData[i,]$steps)) {
      refData[i,]$steps <- getMissingValue(refData[i,]$interval)
   }    
}

summary(refData)

## Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

s3 <- group_by(refData, date)
refStepsperday <- summarize(s3, ST = sum(steps))
print(refStepsperday)

hist(refStepsperday$ST, main = "Total Steps Analysis", col = "green", xlab = "Total Steps")

## Median steps per day in refined data set 
refMedianstepsperday <- median(refStepsperday$ST)

## Mean Steps per day in refined data set 
refMeanstepsperday <- mean(refStepsperday$ST)

print(refMeanstepsperday)
print(refMedianstepsperday)

# The Median Steps had not changed much whereas the mean steps per day in the refined data set by inputting missing values increased by 10% 

```


## Are there differences in activity patterns between weekdays and weekends?

```{r echo = TRUE}
## Create a new factor variable in the dataset with two levels - "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.
refData$day <- weekdays(refData$date)

for (j in 1:nrow(refData)){
    
    if(refData[j,]$day %in% c("Saturday", "Sunday")){
        refData[j,]$day <- "weekend"
    }
    else {
        refData[j,]$day <- "weekday"
    }
}
summary(refData)

##Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.

s4 <- group_by(refData, interval,day)
refSteps <- summarize(s4, stepT = mean(steps))
summary(refSteps)

## To include lattice package for plotting 
library(lattice)

xyplot(stepT ~ interval | day,refSteps, type = "l", layout = c(1,2), xlab = "Interval" , ylab = "Average Number of Steps", main= "Average Steps Analysis across weekend and weekdays" )

```

